apiVersion: v1
kind: ConfigMap
metadata:
  name: kubekavach-config
  namespace: kubekavach
data:
  config.yaml: |
    api:
      host: "0.0.0.0"
      port: 8080
      corsOrigin: "*"
    rules:
      - id: "privileged-containers"
        name: "Privileged Containers"
        description: "Detect containers running in privileged mode"
        severity: "CRITICAL"
        enabled: true
      - id: "root-user"
        name: "Root User"
        description: "Detect containers running as root user"
        severity: "HIGH"
        enabled: true
      - id: "no-resource-limits"
        name: "No Resource Limits"
        description: "Detect containers without resource limits"
        severity: "MEDIUM"
        enabled: true
      - id: "no-readiness-probe"
        name: "No Readiness Probe"
        description: "Detect containers without readiness probes"
        severity: "LOW"
        enabled: true
      - id: "no-liveness-probe"
        name: "No Liveness Probe"
        description: "Detect containers without liveness probes"
        severity: "LOW"
        enabled: true
      - id: "insecure-capabilities"
        name: "Insecure Capabilities"
        description: "Detect containers with dangerous capabilities"
        severity: "HIGH"
        enabled: true
      - id: "host-network"
        name: "Host Network"
        description: "Detect pods using host network"
        severity: "HIGH"
        enabled: true
      - id: "host-pid"
        name: "Host PID"
        description: "Detect pods using host PID namespace"
        severity: "HIGH"
        enabled: true
      - id: "host-ipc"
        name: "Host IPC"
        description: "Detect pods using host IPC namespace"
        severity: "HIGH"
        enabled: true
    database:
      enabled: false  # Set to true for production with PostgreSQL
    logging:
      level: "info"
      format: "json"
    metrics:
      enabled: true
      port: 9090