apiVersion: v1
kind: Secret
metadata:
  name: kubekavach-secrets
  namespace: kubekavach
type: Opaque
data:
  # Base64 encoded API keys and secrets
  # In production, these should be managed by external secret management systems
  # Example: echo -n "your-api-key-here" | base64
  api-key-admin: YWRtaW4ta2V5LWhlcmU=  # admin-key-here
  api-key-scanner: c2Nhbm5lci1rZXktaGVyZQ==  # scanner-key-here
  api-key-viewer: dmlld2VyLWtleS1oZXJl  # viewer-key-here
  
  # Database credentials (if using external database)
  database-host: cG9zdGdyZXNxbA==  # postgresql
  database-port: NTQzMg==  # 5432
  database-name: a3ViZWthdmFjaA==  # kubekavach
  database-username: a3ViZWthdmFjaA==  # kubekavach
  database-password: cGFzc3dvcmQ=  # password (change in production)
  
  # AI provider API keys (optional)
  openai-api-key: ""
  anthropic-api-key: ""
  google-ai-api-key: ""