# Number of replicas for high availability
replicaCount: 3

# Container image configuration
image:
  repository: ghcr.io/gensecaihq/kubekavach
  pullPolicy: IfNotPresent
  tag: "latest"

# Image pull secrets for private registries
imagePullSecrets: []
# - name: regcred

# Service account configuration
serviceAccount:
  create: true
  annotations: {}
  name: ""
  automount: false  # Security best practice

# Pod security context
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 65534  # nobody user
  runAsGroup: 65534
  fsGroup: 65534
  seccompProfile:
    type: RuntimeDefault
  supplementalGroups: []

# Container security context
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65534

# Service configuration
service:
  type: ClusterIP
  port: 80
  targetPort: 3000
  annotations: {}

# Ingress configuration
ingress:
  enabled: false
  className: ""
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    # cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: kubekavach.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: kubekavach-tls
  #    hosts:
  #      - kubekavach.local

# Resource limits and requests
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

# HorizontalPodAutoscaler configuration
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

# Node selection
nodeSelector: {}

# Pod tolerations
tolerations: []

# Pod affinity
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - kubekavach
        topologyKey: kubernetes.io/hostname

# Liveness and readiness probes
livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 3
  failureThreshold: 3

# Pod disruption budget
podDisruptionBudget:
  enabled: true
  minAvailable: 1
  # maxUnavailable: 1

# Network policies
networkPolicy:
  enabled: true
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: kubekavach
      ports:
      - protocol: TCP
        port: 3000
  egress:
    - to: []  # Allow all egress for API calls
      ports:
      - protocol: TCP
        port: 443  # HTTPS
      - protocol: TCP
        port: 53   # DNS
      - protocol: UDP
        port: 53   # DNS

# Application configuration
config:
  api:
    port: 3000
    host: "0.0.0.0"
    corsOrigin: "*"
    rateLimit:
      max: 1000
      timeWindow: "1 minute"
  
  # Security scanner configuration
  scanner:
    maxConcurrentScans: 5
    timeoutSeconds: 300
    retryAttempts: 3
  
  # AI provider configuration (optional)
  ai:
    enabled: false
    provider: "openai"  # openai, anthropic, google, ollama
    model: "gpt-4"
  
  # Replay configuration
  replay:
    enabled: true
    enableNetworkIsolation: true
    cpuLimit: 0.5
    memoryLimit: "512m"
    allowCriticalVulnerabilities: false
    readOnlyRootFilesystem: false

# Monitoring and observability
monitoring:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 30s
    path: /metrics
    labels: {}
  
  # Grafana dashboard
  grafanaDashboard:
    enabled: true
    labels:
      grafana_dashboard: "1"

# Persistence for scan results
persistence:
  enabled: false
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 10Gi
  annotations: {}

# Compliance configuration
compliance:
  certIn:
    enabled: false
    organizationId: ""
    reportingEndpoint: ""
  meity:
    dataLocalization: true
    region: "IN-WEST"
    retentionDays: 90

# Environment variables
env:
  - name: NODE_ENV
    value: "production"
  - name: LOG_LEVEL
    value: "info"

# Extra environment variables from secrets/configmaps
envFrom: []
# - secretRef:
#     name: kubekavach-secrets
# - configMapRef:
#     name: kubekavach-config

# Additional volumes
volumes:
  - name: tmp
    emptyDir: {}
  - name: cache
    emptyDir: {}

# Additional volume mounts
volumeMounts:
  - name: tmp
    mountPath: /tmp
  - name: cache
    mountPath: /app/cache
